version: '3.8'

services:
  app:
    image: ocr-llm:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    environment:
      - REDIS_URL=redis://redis:6379/0
      - USE_GPU=true
      - ENVIRONMENT=production
    volumes:
      - /var/log/ocr-llm:/app/logs
    networks:
      - ocr-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - ocr-network