[project]
name = "ocr-llm-cli"
requires-python = ">=3.10"
dependencies = [
    "pymupdf==1.24.2",
    "pydantic>=2",
    "pydantic-settings",
    "python-dotenv",
    "rich",
    "click>=8.0",
    "dependency-injector>=4.41",
    "transformers>=4.38.2",
    "pdf2image",
    "pillow",
    "torch",
    # Monitoring and logging
    "opentelemetry-api>=1.20.0",
    "opentelemetry-sdk>=1.20.0",
    "opentelemetry-instrumentation>=0.41b0",
    "structlog>=23.1.0",
    "prometheus-client>=0.17.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "isort",
    "mypy",
]

[project.scripts]
ocr-llm = "src.interfaces.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=src"

[tool.coverage.run]
source = ["src"]