[project]
name = "ocr-llm-cli"
requires-python = ">=3.10"
dependencies = [
  "openai>=1.11",
  "pymupdf==1.24.2",
  "pytesseract",
  "pydantic>=2",
  "python-dotenv",
  "rich",        # CLI bonita (opcional)
]